apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: django-app-new-django-app
  namespace: django-app
spec:
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
