pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      command:
        - /busybox/cat
      tty: true
"""
        }
    }

    environment {
        ECR_REPO_URL = '685873929524.dkr.ecr.eu-west-2.amazonaws.com/lesson-7-ecr'
        AWS_DEFAULT_REGION = 'eu-west-2'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'final-project', url: 'https://github.com/maksar24/hw_devops_goit.git'
            }
        }

        stage('Build & Push Image') {
            steps {
                container('kaniko') {
                    sh """
                    /kaniko/executor \
                      --dockerfile=Dockerfile \
                      --context=. \
                      --destination=$ECR_REPO_URL:latest
                    """
                }
            }
        }
    }
}
