pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-kaniko
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.16.0-debug
      imagePullPolicy: Always
      command:
        - sleep
      args:
        - 99d
      volumeMounts:
        - name: workspace
          mountPath: /workspace
    - name: git
      image: alpine/git
      command:
        - sleep
      args:
        - 99d
      volumeMounts:
        - name: workspace
          mountPath: /workspace
  volumes:
    - name: workspace
      emptyDir: {}
"""
        }
    }

    environment {
        ECR_REPO_URL = '685873929524.dkr.ecr.eu-west-2.amazonaws.com/lesson-7-ecr'
        IMAGE_TAG    = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                container('git') {
                    sh '''
                        git clone -b final-project https://github.com/maksar24/hw_devops_goit.git /workspace
                    '''
                }
            }
        }

        stage('Build & Push Image') {
            steps {
                container('kaniko') {
                    sh '''
                        /kaniko/executor \
                          --dockerfile=/workspace/django-app/Dockerfile \
                          --context=/workspace/django-app \
                          --destination=$ECR_REPO_URL:$IMAGE_TAG \
                          --cache=true
                    '''
                }
            }
        }
    }
}
