apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-app
  namespace: {{ .Release.Namespace }}
spec:
  project: default
  source:
    repoURL: "{{ .Values.repo_url }}"
    targetRevision: lesson-7
    path: charts/django-app
  destination:
    server: https://kubernetes.default.svc
    namespace: django-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
